<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = array(
            array(
                'name' => 'Admin',
                'email' => 'admin@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'System Administrator',
                'position' => 'CAA-II',
                "assigned_muni_code" => null,
                "assigned_district_id" => null,
            ),
            array(
                'name' => 'alaminos',
                'email' => 'alaminos@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043401',
                'assigned_district_id' => 3,
            ),
            array(
                'name' => 'bay',
                'email' => 'bay@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043402',
                'assigned_district_id' => 2,
            ),
            array(
                'name' => 'binan',
                'email' => 'binan@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043403',
                'assigned_district_id' => 1,
            ),
            array(
                'name' => 'cabuyao',
                'email' => 'cabuyao@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043404',
                'assigned_district_id' => 1,
            ),
            array(
                'name' => 'calamba',
                'email' => 'calamba@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043405',
                'assigned_district_id' => 2,
            ),
            array(
                'name' => 'calauan',
                'email' => 'calauan@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043406',
                'assigned_district_id' => 2,
            ),
            array(
                'name' => 'cavinti',
                'email' => 'cavinti@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043407',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'kalayaan',
                'email' => 'kalayaan@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043409',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'liliw',
                'email' => 'liliw@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043410',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'losbanos',
                'email' => 'losbanos@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043411',
                'assigned_district_id' => 2,
            ),
            array(
                'name' => 'luisiana',
                'email' => 'luisiana@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043412',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'lumban',
                'email' => 'lumban@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043413',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'mabitac',
                'email' => 'mabitac@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043414',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'magdalena',
                'email' => 'magdalena@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043415',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'majayjay',
                'email' => 'majayjay@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043416',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'nagcarlan',
                'email' => 'nagcarlan@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043417',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'famy',
                'email' => 'famy@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043408',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'paete',
                'email' => 'paete@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043418',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'pagsanjan',
                'email' => 'pagsanjan@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043419',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'pakil',
                'email' => 'pakil@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043420',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'pangil',
                'email' => 'pangil@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043421',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'pila',
                'email' => 'pila@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043422',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'rizal',
                'email' => 'rizal@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043423',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'sanpablo',
                'email' => 'sanpablo@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043424',
                'assigned_district_id' => 3,
            ),
            array(
                'name' => 'sanpedro',
                'email' => 'sanpedro@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043425',
                'assigned_district_id' => 1,
            ),
            array(
                'name' => 'santacruz',
                'email' => 'santacruz@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043426',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'santamaria',
                'email' => 'santamaria@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043427',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'santarosa',
                'email' => 'santarosa@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043428',
                'assigned_district_id' => 1,
            ),
            array(
                'name' => 'siniloan',
                'email' => 'siniloan@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043429',
                'assigned_district_id' => 4,
            ),
            array(
                'name' => 'victoria',
                'email' => 'victoria@gmail.com',
                'password' => Hash::make('password'),
                'mobile' => '+639123456789',
                'classification' => 'Encoder',
                'position' => 'City / Municipality Representative',
                'assigned_muni_code' => '043430',
                'assigned_district_id' => 3,
            ),
        );

        DB::table('tbl_users')->insert($users);
    }
}
