<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VolunteerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      	$volunteers = array(
		  	array(
			    'position_id' => 2,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'first_name' => 'Florence',
			    'middle_name' => 'Pascua',
			    'last_name' => 'Dela Cruz',
			    'suffix' => '',
			    'sex' => 'Female',
			    'birth_date' => '1996-01-22',
			    'address' => '4452  Thomas Street',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
		  	),
			array(
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'first_name' => 'Katherine ',
			    'middle_name' => 'De Vera',
			    'last_name' => 'Villanueva',
			    'suffix' => '',
			    'sex' => 'Female',
			    'birth_date' => '1996-01-23',
			    'address' => '4419  Lowndes Hill Park Road',
			    'mobile' => 9123456790,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456790,
			),
			array(
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'first_name' => 'Cooper',
			    'middle_name' => 'Alcantara',
			    'last_name' => 'Bautista',
			    'suffix' => '',
			    'sex' => 'Male',
			    'birth_date' => '1996-01-24',
			    'address' => '3715  Locust Street',
			    'mobile' => 9123456791,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456791,
			  ),
			array(
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'first_name' => 'Sadie',
			    'middle_name' => 'Ocampo',
			    'last_name' => 'De Guzman',
			    'suffix' => '',
			    'sex' => 'Female',
			    'birth_date' => '1996-01-25',
			    'address' => '213  Hillcrest Circle',
			    'mobile' => 9123456792,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456792,
			),
			array(
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'first_name' => 'Penny',
			    'middle_name' => 'Ignacio',
			    'last_name' => 'Lopez',
			    'suffix' => '',
			    'sex' => 'Female',
			    'birth_date' => '1996-01-26',
			    'address' => '1298  Carriage Court',
			    'mobile' => 9123456793,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456793,
			  ),
			array(
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'first_name' => 'Ellie',
			    'middle_name' => 'Legaspi',
			    'last_name' => 'Perez',
			    'suffix' => '',
			    'sex' => 'Male',
			    'birth_date' => '1996-01-27',
			    'address' => '2206  Simpson Street',
			    'mobile' => 9123456794,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456794,
			),
			array(
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'first_name' => 'Diesel',
			    'middle_name' => 'Samson',
			    'last_name' => 'Rivera',
			    'suffix' => '',
			    'sex' => 'Male',
			    'birth_date' => '1996-01-28',
			    'address' => '2031  Adonais Way',
			    'mobile' => 9123456795,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456795,
			),
			array(
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'first_name' => 'Rosie',
			    'middle_name' => 'Peralta',
			    'last_name' => 'Castro',
			    'suffix' => '',
			    'sex' => 'Female',
			    'birth_date' => '1996-01-29',
			    'address' => '4355  New Street',
			    'mobile' => 9123456796,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456796,
			),
			array(
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'first_name' => 'Moose',
			    'middle_name' => 'Francisco',
			    'last_name' => 'Domingo',
			    'suffix' => '',
			    'sex' => 'Male',
			    'birth_date' => '1996-01-30',
			    'address' => '4949  Whitetail Lane',
			    'mobile' => 9123456797,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456797,
			),
			array(
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'first_name' => 'Finn',
			    'middle_name' => 'Aguilar',
			    'last_name' => 'Martinez',
			    'suffix' => '',
			    'sex' => 'Male',
			    'birth_date' => '1996-01-31',
			    'address' => '2297  Timber Ridge Road',
			    'mobile' => 9123456798,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456798,
			),
			array(
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'first_name' => 'Blue',
			    'middle_name' => 'Gomez',
			    'last_name' => 'Diaz',
			    'suffix' => '',
			    'sex' => 'Female',
			    'birth_date' => '1996-02-01',
			    'address' => '3230  Arbutus Drive',
			    'mobile' => 9123456799,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456799,
			),
			array(
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'first_name' => 'Peanut',
			    'middle_name' => 'Palma',
			    'last_name' => 'Miranda',
			    'suffix' => '',
			    'sex' => 'Male',
			    'birth_date' => '1996-02-02',
			    'address' => '4494  Hott Street',
			    'mobile' => 9123456800,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456800,
			),
		
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Male',
			    'first_name' => 'Joshua',
			    'middle_name' => 'Manuel',
			    'last_name' => 'Ramos',
			    'suffix' => '',
			    'birth_date' => '1996-01-22',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Male',
			    'first_name' => 'Paul',
			    'middle_name' => 'Pineda',
			    'last_name' => 'Castillo',
			    'suffix' => '',
			    'birth_date' => '1996-01-23',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Male',
			    'first_name' => 'John',
			    'middle_name' => 'Ocampo',
			    'last_name' => 'Reyes',
			    'suffix' => '',
			    'birth_date' => '1996-01-24',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Male',
			    'first_name' => 'Mark',
			    'middle_name' => 'Enriquez',
			    'last_name' => 'Perez',
			    'suffix' => '',
			    'birth_date' => '1996-01-25',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Male',
			    'first_name' => 'Kenneth',
			    'middle_name' => 'Alcantara',
			    'last_name' => 'Francisco',
			    'suffix' => '',
			    'birth_date' => '1996-01-26',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Male',
			    'first_name' => 'Ryan',
			    'middle_name' => 'Pasco',
			    'last_name' => 'Rivera',
			    'suffix' => '',
			    'birth_date' => '1996-01-27',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Male',
			    'first_name' => 'Jerome',
			    'middle_name' => 'Pascua',
			    'last_name' => 'De Guzman',
			    'suffix' => '',
			    'birth_date' => '1996-01-28',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Male',
			    'first_name' => 'Adrian',
			    'middle_name' => 'Valencia',
			    'last_name' => 'Martinez',
			    'suffix' => '',
			    'birth_date' => '1996-01-29',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Male',
			    'first_name' => 'Frank',
			    'middle_name' => 'Espiritu',
			    'last_name' => 'Domingo',
			    'suffix' => '',
			    'birth_date' => '1996-01-30',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Female',
			    'first_name' => 'Angel',
			    'middle_name' => 'Domingo',
			    'last_name' => 'De Leon',
			    'suffix' => '',
			    'birth_date' => '1996-01-31',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Female',
			    'first_name' => 'Maria',
			    'middle_name' => 'Peralta',
			    'last_name' => 'Diaz',
			    'suffix' => '',
			    'birth_date' => '1996-02-01',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Female',
			    'first_name' => 'Kyla',
			    'middle_name' => 'Ibanez',
			    'last_name' => 'Hernandez',
			    'suffix' => '',
			    'birth_date' => '1996-02-02',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Female',
			    'first_name' => 'Joy',
			    'middle_name' => 'Vargas',
			    'last_name' => 'Tolentino',
			    'suffix' => '',
			    'birth_date' => '1996-02-03',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Female',
			    'first_name' => 'Nicole',
			    'middle_name' => 'Legaspi',
			    'last_name' => 'Morales',
			    'suffix' => '',
			    'birth_date' => '1996-02-04',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Female',
			    'first_name' => 'Love',
			    'middle_name' => 'Gonzales',
			    'last_name' => 'Ramirez',
			    'suffix' => '',
			    'birth_date' => '1996-02-05',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Female',
			    'first_name' => 'Chris',
			    'middle_name' => 'Espinosa',
			    'last_name' => 'Tan',
			    'suffix' => '',
			    'birth_date' => '1996-02-06',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Male',
			    'first_name' => 'Chirstian',
			    'middle_name' => 'Molina',
			    'last_name' => 'Aguilar',
			    'suffix' => '',
			    'birth_date' => '1996-02-07',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Female',
			    'first_name' => 'Kim',
			    'middle_name' => 'Serrano',
			    'last_name' => 'Manalo',
			    'suffix' => '',
			    'birth_date' => '1996-02-08',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Female',
			    'first_name' => 'Jess',
			    'middle_name' => 'Medina',
			    'last_name' => 'Navarro',
			    'suffix' => '',
			    'birth_date' => '1996-02-09',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Female',
			    'first_name' => 'Tin',
			    'middle_name' => 'Palma',
			    'last_name' => 'Gomez',
			    'suffix' => '',
			    'birth_date' => '1996-02-10',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Male',
			    'first_name' => 'Ray',
			    'middle_name' => 'Tamayo',
			    'last_name' => 'Corpuz',
			    'suffix' => '',
			    'birth_date' => '1996-02-11',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ), 
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Female',
			    'first_name' => 'Trisha',
			    'middle_name' => 'Atienza',
			    'last_name' => 'Javier',
			    'suffix' => '',
			    'birth_date' => '1996-02-12',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Male',
			    'first_name' => 'Lloyd',
			    'middle_name' => 'Martin',
			    'last_name' => 'Ferrer',
			    'suffix' => '',
			    'birth_date' => '1996-02-13',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Male',
			    'first_name' => 'Ben',
			    'middle_name' => 'Ortiz',
			    'last_name' => 'Alvarez',
			    'suffix' => '',
			    'birth_date' => '1996-02-14',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456789,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456789,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Female',
			    'first_name' => 'Jane',
			    'middle_name' => 'Rivera',
			    'last_name' => 'Sison',
			    'suffix' => '',
			    'birth_date' => '1996-02-15',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456790,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456790,
			  ), 
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Female',
			    'first_name' => 'Rose',
			    'middle_name' => 'Ortiz',
			    'last_name' => 'Zamora',
			    'suffix' => '',
			    'birth_date' => '1996-02-16',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456791,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456791,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Female',
			    'first_name' => 'Margareth',
			    'middle_name' => 'Ortiz',
			    'last_name' => 'Abad',
			    'suffix' => '',
			    'birth_date' => '1996-02-17',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456792,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456792,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Female',
			    'first_name' => 'Cyn',
			    'middle_name' => 'Bernardo',
			    'last_name' => 'Concepcion',
			    'suffix' => '',
			    'birth_date' => '1996-02-18',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456793,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456793,
			  ),
			  array (
			    'position_id' => 1,
			    'district_id' => 1,
			    'municipality_code' => 43425,
			    'barangay_code' => 43425026,
			    'sex' => 'Male',
			    'first_name' => 'Jojo',
			    'middle_name' => 'Domingo',
			    'last_name' => 'Fernando',
			    'suffix' => '',
			    'birth_date' => '1996-02-19',
			    'address' => 'Mapayapa St.',
			    'mobile' => 9123456794,
			    'contact_person_name' => 'Juan Dela Cruz',
			    'contact_person_mobile' => 9123456794,
			  ),
		);

		DB::table('tbl_volunteers')->insert($volunteers);
    }
}
